; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
include_dir = Inc
src_dir = Src
default_envs = nucleo_f446ze_eth	; switch to whatever you are using the debugger for at the present time.

[env]
platform = ststm32
framework = stm32cube
lib_archive = no
lib_ldf_mode = off
upload_protocol = stlink
debug_tool = stlink

[global]
build_flags = 
	-I FATFS/App				
	-I FATFS/Target
	-I Middlewares/Third_Party/FatFs/src
lib_deps = 
	file://FATFS/App
	file://FATFS/Target
	file://Middlewares/Third_Party/FatFs
	bblanchon/ArduinoJson@^7.4.1

[W5500_eth]
extends = global
build_flags = 
    -D ETH_CTRL=1 ; choose between ETH_CTRL=1 or SPI_CTRL=1 for config uploading and LinuxCNC control.
	-D _WIZCHIP_=5500
lib_deps = 
	W5500_Networking=file://Src/remora-core/drivers/W5500_Networking/W5500_Networking.zip


[generic_411]		
board = genericSTM32F411CE
board_build.mcu = stm32f411cet6
build_flags = 
	${global.build_flags}
	-D GENERIC_F411=1
	-D HAS_BOOTLOADER=1
	-D HSE_VALUE=8000000U		
	-D UART_PORT=USART1
lib_deps = 
	${global.lib_deps}


[nucleo_f411]		
build_flags = 
	${global.build_flags}
	-D NUCLEO_F411=1
	-D HSE_VALUE=8000000U		
	-D SPI_CS_IRQ=EXTI4_IRQn	
	-D SPI_CS="\"PA_4"\"
	-D SPI_CLK="\"PA_5"\"
	-D SPI_MISO="\"PA_6"\"
	-D SPI_MOSI="\"PA_7"\"
lib_deps = ${global.lib_deps}

[env:nucleo_f411ce_spi]
extends = nucleo_f411
board = nucleo_f411ce
board_build.ldscript = LinkerScripts/STM32F411XX_SPICOMMS_NOBL.ld
build_flags = 
	${nucleo_f411.build_flags}
	-D SPI_CTRL=1
	-D UART_PORT=USART2


[generic_407]		
board = genericSTM32F407VE
board_build.mcu = stm32f407vet6
build_flags = 
	${global.build_flags}
	-D GENERIC_F407=1
	-D HAS_BOOTLOADER=1
	-D HSE_VALUE=8000000U		
	-D UART_PORT=USART1
lib_deps = 
	${global.lib_deps}

[generic_429]		
board = genericSTM32F429VE
board_build.mcu = stm32f429vet6
build_flags = 
	${global.build_flags}
	-D GENERIC_F429=1
	-D HAS_BOOTLOADER=1
	-D HSE_VALUE=8000000U		
	-D UART_PORT=USART1
lib_deps = 
	${global.lib_deps}




[generic_446]		
board = genericSTM32F446RE
board_build.mcu = stm32f446zet6
build_flags = 
	${global.build_flags}
	-D GENERIC_F446=1
	-D HAS_BOOTLOADER=1
	-D HSE_VALUE=12000000U		
	-D UART_PORT=USART1
lib_deps = 
	${global.lib_deps}

[octopus_spi]
build_flags = 
    -D SPI_CTRL=1
	-D SPI_CS_IRQ=EXTI4_IRQn	; Note that this is for SPI builds but is required in both built target master types.			
	-D SPI_CS="\"PA_4"\"
	-D SPI_CLK="\"PA_5"\"
	-D SPI_MISO="\"PA_6"\"
	-D SPI_MOSI="\"PA_7"\"

[octopus_eth]
build_flags = 
	${W5500_eth.build_flags}	
	-D SPI_CS_IRQ=EXTI4_IRQn	; Note that this is for SPI builds but is required in both built target master types.
	-D SPI_CS="\"PA_4"\"
	-D SPI_CLK="\"PB_13"\"
	-D SPI_MISO="\"PB_14"\"
	-D SPI_MOSI="\"PB_15"\"
	-D WIZ_RST="\"PB_5"\"
lib_deps = 
	${W5500_eth.lib_deps}

[env:Octopus_429_spi]		
extends = generic_429
board_build.ldscript = LinkerScripts/STM32F429XX_SPICOMMS_OCTOPUS_BL.ld 
build_flags = 
	${generic_429.build_flags}
	${octopus_spi.build_flags}

[env:Octopus_429_eth]
extends = generic_429	
board_build.ldscript = LinkerScripts/STM32F446XX_SPICOMMS_OCTOPUS_BL.ld 
board_upload.maximum_size = 491520
build_flags = 
	${generic_429.build_flags}
	${octopus_eth.build_flags}

[env:Octopus_446_spi]		
extends = generic_446
board_build.ldscript = LinkerScripts/STM32F429XX_SPICOMMS_OCTOPUS_BL.ld 
build_flags = 
	${generic_446.build_flags}
	${octopus_spi.build_flags}


[env:Octopus_446_eth]
extends = generic_446	
board_build.ldscript = LinkerScripts/STM32F446XX_SPICOMMS_OCTOPUS_BL.ld 
board_upload.maximum_size = 491520
build_flags = 
	${generic_446.build_flags}
	${octopus_eth.build_flags}



[env:Spider_446_spi]		
extends = generic_446
board_build.ldscript = LinkerScripts/STM32F446XX_SPICOMMS_OCTOPUS_BL.ld 
build_flags = 
	${generic_446.build_flags}
    -D SPI_CTRL=1
	-D SPI_CS_IRQ=EXTI9_5_IRQn	; Note that this is for SPI builds but is required in both built target master types.			
	-D SPI_CS="\"PC_6"\"
	-D SPI_CLK="\"PA_5"\"
	-D SPI_MISO="\"PA_6"\"
	-D SPI_MOSI="\"PA_7"\"



[nucleo_f446]		
build_flags = 
	${global.build_flags}
	-D NUCLEO_F446=1
	-D HSE_VALUE=8000000U		
	-D SPI_CS_IRQ=EXTI4_IRQn	
	-D SPI_CS="\"PA_4"\"
	-D SPI_CLK="\"PA_5"\"
	-D SPI_MISO="\"PA_6"\"
	-D SPI_MOSI="\"PA_7"\"
lib_deps = ${global.lib_deps}

; Build targets for Nucleo F446re
[env:nucleo_f446re_eth]
extends = nucleo_f446
board = nucleo_f446re
board_build.ldscript = LinkerScripts/STM32F446XX_ETHCOMMS_NOBL.ld 
board_upload.maximum_size = 475136   
build_flags = 
	${nucleo_f446.build_flags}
	${W5500_eth.build_flags}
	-D UART_PORT=USART2
	-D WIZ_RST="\"PB_5"\"
lib_deps = 
	${W5500_eth.lib_deps}


[env:nucleo_f446re_spi]
extends = nucleo_f446
board = nucleo_f446re
board_build.ldscript = LinkerScripts/STM32F446XX_SPICOMMS_NOBL.ld
build_flags = 
	${nucleo_f446.build_flags}
	-D SPI_CTRL=1
	-D UART_PORT=USART2

[env:nucleo_f446ze_eth]
extends = nucleo_f446
board = nucleo_f446ze
board_build.ldscript = LinkerScripts/STM32F446XX_ETHCOMMS_NOBL.ld 
board_upload.maximum_size = 475136   
build_flags = 
	${nucleo_f446.build_flags}
	${W5500_eth.build_flags}
	-D UART_PORT=USART3
	-D WIZ_RST="\"PB_5"\"
lib_deps = 
	${W5500_eth.lib_deps}


[env:nucleo_f446ze_spi]
extends = nucleo_f446
board = nucleo_f446ze
board_build.ldscript = LinkerScripts/STM32F446XX_SPICOMMS_NOBL.ld
build_flags = 
	${nucleo_f446.build_flags}
	-D SPI_CTRL=1
	-D UART_PORT=USART3


[env:nucleo_f446re_cakelob]	
board = nucleo_f446re
board_build.ldscript = LinkerScripts/STM32F446XX_SPICOMMS_NOBL.ld
build_flags = 
	${global.build_flags}
	-D NUCLEO_F446=1
	-D SPI_CTRL=1
	-D UART_PORT=USART2
	-D HSE_VALUE=8000000U		
	-D SPI_CS_IRQ=EXTI1_IRQn
	-D SPI_CS="\"PB_1"\"
	-D SPI_CLK="\"PB_13"\"
	-D SPI_MISO="\"PB_14"\"
	-D SPI_MOSI="\"PB_15"\"
lib_deps = ${global.lib_deps}


